version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"  # Adjust the Python version if needed
sphinx:
  configuration: docs/conf.py  # Update the path if conf.py is elsewhere
python:
  install:
    - requirements: requirements.txt
